### PR TITLE
updated app js

### PR DESCRIPTION
**Pull request by Sabina-Kazantseva**

### CODE REVIEW

**Review by MalinSP — COMMENTED** [review]
Screenshot 2023-11-27 at 8 55 12 AM
It still add twice when you add a task. Please, take a look on a previous response with explanation

**Comment by Sabina-Kazantseva** [comment]
Hi. There is no previous response.

**Comment by MalinSP** [comment]
Screenshot 2023-11-27 at 11 08 55 AM
I guess you fixed something because now it's working great

**Comment by Sabina-Kazantseva** [comment]
Do I have to submit assignment again???

**Pull request merged**
